[package]
name = "cheminee-similarity-weights"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1"
eyre = "0"
lazy_static = "1.5.0"
ndarray = "0.16.1"
tempfile = "3.13.0"
tensorflow = "0.21.0"
